pip install pandas
pip install numpy
pip install matplotlib
pip install seaborn
pip install scikit-learn
pip install xgboost
pip install keras
pip install tensorflow
pip install nltk
pip install torch torchvision
pip install spacy
pip install pytorch-lightning
pip install scikit-image
pip install opencv-python
pip install pillow
pip install requests
pip install beautifulsoup4
pip install flask
pip install django
pip install fastapi
pip install streamlit
pip install jupyter
pip install jupyterlab
pip install boto3
pip install google-cloud-storage
pip install azure-storage-blob
pip install langchain
pip install openai
pip install tiktoken
pip install chromadb
